
#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.url=jdbc:mysql://localhost:3306/testdb?&useUnicode=true&serverTimezone=Asia/Kolkata

#spring.datasource.url=jdbc:mysql://localhost:3306/expense
#spring.datasource.username=root
#spring.datasource.password=root
#spring.jackson.time-zone=IST
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect



spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Dialect (often automatically detected by Spring Boot, but good to be explicit)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Adjust DDL auto as needed (validate, update, create, create-drop, none)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.org.hibernate=DEBUG




#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.url=jdbc:mysql://localhost:3306/vminventory?&useUnicode=true&useJDBCCompliantTimezoneShift=true&serverTimezone=IST&useLegacyDatetimeCode=false
#spring.datasource.username=root
#spring.datasource.password=root
#spring.jackson.time-zone=IST




#spring.datasource.url=jdbc:h2:~/test
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=password
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.h2.console.enabled=true


#spring.datasource.url = jdbc:sqlite:test.db
#spring.datasource.driver-class-name = org.sqlite.JDBC
#spring.datasource.username =
#spring.datasource.password =
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.database-platform=com.kmsoft.dialect.SQLDialect
#spring.datasource.initialization-mode=always
#spring.jpa.properties.hibernate.dialect =com.kmsoft.dialect.SQLDialect

#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.url=jdbc:mysql://localhost:3306/invsoft?&useUnicode=true&useJDBCCompliantTimezoneShift=true&serverTimezone=IST&useLegacyDatetimeCode=false
#spring.datasource.username=root
#spring.datasource.password=Mithulya16*
#spring.jackson.time-zone=IST

#spring.datasource.url=jdbc:h2:~/test
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=password
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.h2.console.enabled=true

#spring.jpa.database-platform=com.springboot.sqlite.SQLDialect
#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.url = jdbc:sqlite:INVSOFT_DEV.db
#spring.datasource.driver-class-name = org.sqlite.JDBC
#spring.datasource.username = admin
#spring.datasource.password = admin

